apiVersion: apps/v1
kind: Deployment
metadata:
  name: mackerel-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mackerel-operator
  template:
    metadata:
      labels:
        name: mackerel-operator
    spec:
      serviceAccountName: mackerel-operator
      containers:
        - name: mackerel-operator
          # Replace this with the built image name
          image: chokkoy/mackerel-operator:v0.0.1
          command:
          - mackerel-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mackerel-operator"
